# Generated by Django 3.2.12 on 2022-09-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20220917_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
